source:
  copy_from:
    - "README.md"
    - ".gitignore"
    - "book"
target:
  repo: "duerrsimon/jb_clone_public"
  maxsize_commit_MB: 1000
  commit_message: "publish student version"
  copy_to:
    - "README.md"
    - ".gitignore"
    - "book"
  remove_after_copy:
    - "book/Exercises/Exercise1_instructor.md"
