name: Publish Repo

on:
  push:
    branches:
    - 'main'
  workflow_dispatch:

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
    - name: Push to public student repo
      uses: duerrsimon/repo_selective_sync_remove_solutions@master
      with:
        recipe-file: '.publish/recipe.yml'
        token-source: ${{ secrets.GITHUB_TOKEN }}
        token-target: ${{ secrets.TARGET_PAT }}
